import type { ReactNode } from "react";
import type {
  DeepSelectionInfo as StoreDeepSelectionInfo,
  DeepSelectionInput as StoreDeepSelectionInput,
} from "../../store/slices/selection";

// Re-export base types for convenience
export type { StoreDeepSelectionInfo as DeepSelectionInfoBase };
export type { StoreDeepSelectionInput as DeepSelectionInputBase };

// ─────────────────────────────────────────────────────────────────────────────
// Selectable Item Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Data about a selectable item (used in selection logic)
 */
export interface SelectableItemData {
  /** Unique identifier for this item */
  itemId: string;
  /** The parent element's key */
  elementKey: string;
  /** Optional data associated with this item */
  data?: unknown;
  /** DOM element reference (if available) */
  element?: HTMLElement;
}

/**
 * Represents a selected item
 */
export interface SelectedItem {
  /** Unique identifier for this item */
  itemId: string;
  /** The parent element's key */
  elementKey: string;
  /** Optional data associated with this item */
  data?: unknown;
}

// ─────────────────────────────────────────────────────────────────────────────
// Deep Selection Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Deep selection with DOM element reference.
 *
 * Extends the serializable store type with an optional HTMLElement reference.
 * The element is reconstructed on-demand via findElementByCssPath() and is NOT
 * stored in Zustand (immer cannot handle DOM nodes).
 */
export interface DeepSelectionInfo extends StoreDeepSelectionInfo {
  /** The actual DOM element reference (computed on-demand, not stored) */
  element?: HTMLElement | null;
}

/**
 * Input for creating a selection with optional DOM element.
 * id and timestamp are generated by the store.
 */
export interface DeepSelectionInput extends StoreDeepSelectionInput {
  /** DOM element reference (for tracking, not stored in Zustand) */
  element?: HTMLElement | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Context Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Selection context value type
 */
export interface SelectionContextValue {
  /** Map of elementKey -> Set of selected itemIds (derived from Zustand) */
  granularSelection: Record<string, Set<string>>;
  /** Toggle selection of an item within an element */
  toggleSelection: (elementKey: string, itemId: string) => void;
  /** Clear selection for a specific element or all */
  clearSelection: (elementKey?: string) => void;
  /** Check if an item is selected */
  isSelected: (elementKey: string, itemId: string) => boolean;
  /** Get all selected item IDs for an element */
  getSelectedItems: (elementKey: string) => string[];
  /** Current deep selections (multiple elements can be selected) */
  deepSelections: DeepSelectionInfo[];
  /** Clear all deep selections */
  clearDeepSelection: () => void;
  /** Check if deep selection is currently active (prevents component-level selection) */
  isDeepSelectionActive: () => boolean;
}

/**
 * Props for SelectionProvider
 */
export interface SelectionProviderProps {
  children: ReactNode;
}

/**
 * Props for the SelectableItem component
 */
export interface SelectableItemProps {
  /** The parent element's key (from element.key) */
  elementKey: string;
  /** Unique identifier for this item within the parent */
  itemId: string;
  /** Children to render inside the selectable wrapper */
  children: ReactNode;
  /** HTML element to render as (default: 'div') */
  as?: React.ElementType;
  /** Additional CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Additional props to spread onto the element */
  [key: string]: unknown;
}
